// <auto-generated />
namespace Casgem_CodeFirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_social_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_social_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202307151302390_mig_social_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
